HmIpMonitor/HmIpMonitor/Models/CreateDeviceParameterModel.cs
using HmIpMonitor.EntityFramework.Models;

namespace HmIpMonitor.Models
{
    public class CreateDeviceParameterModel : DeviceParameter
    {
        public string DeviceName { get; set; }
    }
}

HmIpMonitor/HmIpMonitor/Models/CreateEditDashboardDeviceModel.cs
using System.Collections.Generic;

namespace HmIpMonitor.Models
{
    public class CreateEditDashboardDeviceModel
    {
        public string Title { get; set; }

        public List<CreateEditDashboardDeviceParameterModel> Parameters { get; set; } =
            new List<CreateEditDashboardDeviceParameterModel>();
    }
}

HmIpMonitor/HmIpMonitor/Models/CreateEditDashboardDeviceParameterModel.cs
namespace HmIpMonitor.Models
{
    public class CreateEditDashboardDeviceParameterModel
    {
        public long Id { get; set; }
        public string Parameter { get; set; }
        public bool Active { get; set; }
    }
}

HmIpMonitor/HmIpMonitor/Models/CreateEditDashboardModel.cs
using System.Collections.Generic;

namespace HmIpMonitor.Models
{
    public class CreateEditDashboardModel
    {
        public long Id { get; set; }
        public string Title { get; set; }
        // contains all deviceparameters from database, ordered by deviceid
        public List<CreateEditDashboardDeviceModel> DeviceParameters { get; set; }
    }
}

HmIpMonitor/HmIpMonitor/Models/DeviceIndexModel.cs
using System.Collections.Generic;
using HmIpMonitor.EntityFramework.Models;

namespace HmIpMonitor.Models
{
    public class DeviceIndexModel
    {
        public string Title { get; set; }
        public string Address { get; set; }
        public List<DeviceParameter> DeviceParameter { get; set; }
    }
}

HmIpMonitor/HmIpMonitor/Models/ErrorViewModel.cs
using System;

namespace HmIpMonitor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HmIpMonitor/HmIpMonitor/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HmIpMonitor.Contracts;
using HmIpMonitor.EntityFramework.Models;
using HmIpMonitor.Logic;
using HmIpMonitor.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace HmIpMonitor.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDeviceLogic _deviceLogic;
        private readonly IDashboardLogic _dashboardLogic;

        public DashboardController(IDeviceLogic deviceLogic, IDashboardLogic dashboardLogic)
        {
            _deviceLogic = deviceLogic;
            _dashboardLogic = dashboardLogic;
        }

        public IActionResult Index(long id = 0)
        {
            if (id == 0)
            {
                return View(_dashboardLogic.LoadAll());
            }
            else
            {
                return RedirectToAction("Details", new { Id = id });
            }
        }

        [HttpGet]
        public IActionResult Create(long id = 0)
        {
            return View(GetDashboardModel(id));
        }

        [HttpGet]
        public IActionResult Details(long id)
        {
            return View(id);
        }

        [HttpGet]
        public PartialViewResult CarPartial(long id)
        {
            return new PartialViewResult
            {
                ViewName = "_DashboardDetailsPartial",
                ViewData = new ViewDataDictionary<List<CcuValueDto>>(ViewData, _dashboardLogic.GetAllValues(id))
            };
        }

        [HttpPost]
        public IActionResult Create(CreateEditDashboardModel model)
        {
            _dashboardLogic.SaveOrUpdate(model.Id, model.Title, model.DeviceParameters.SelectMany(x => x.Parameters.Where(x => x.Active)).Select(x => x.Id).ToList());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(long id)
        {
            _dashboardLogic.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            return RedirectToAction("Create", new { Id = id });
        }

        private CreateEditDashboardModel GetDashboardModel(long id = 0)
        {
            CreateEditDashboardModel dashboard = new();
            Dashboard dbDashboard = null;

            if (id > 0)
            {
                dashboard.Id = id;
                dbDashboard = _dashboardLogic.Load(id);
                dashboard.Title = dbDashboard.Title;
            }

            var parameters = _deviceLogic.GetAll().Select(d =>
            {
                var deviceName = _deviceLogic.GetDeviceData(d.Id).Title;
                return new CreateEditDashboardDeviceModel
                {
                    Title = deviceName,
                    Parameters = d.DeviceParameter.Select(dp =>
                    {
                        return new CreateEditDashboardDeviceParameterModel
                        {
                            Parameter = dp.Parameter,
                            Active = dbDashboard?.DashboardDeviceParameters.Any(x => x.DeviceParameterId == dp.Id) ??
                                     false,
                            Id = dp.Id
                        };
                    }).ToList()
                };
            }).ToList();

            dashboard.DeviceParameters = parameters;
            return dashboard;
        }
    }
}

HmIpMonitor/HmIpMonitor/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using HmIpMonitor.Contracts;
using HmIpMonitor.EntityFramework.Models;
using HmIpMonitor.Logic;
using HmIpMonitor.Models;
using Microsoft.AspNetCore.Http;

namespace HmIpMonitor.Controllers
{
    public class DeviceController : Controller
    {
        private readonly IDeviceLogic _deviceLogic;

        public DeviceController(IDeviceLogic deviceLogic)
        {
            _deviceLogic = deviceLogic;
        }

        public IActionResult Index()
        {
            var model = _deviceLogic.GetAll().Select(d =>
            {
                var deviceData = _deviceLogic.GetDeviceData(d.Id);
                return new DeviceIndexModel
                {
                    Address = deviceData.Address,
                    DeviceParameter = d.DeviceParameter.OrderBy(x => x.Parameter).ToList(),
                    Title = deviceData.Title
                };
            });
            return View(model);
        }

        [HttpGet]
        public ActionResult Create(int id = 0)
        {
            if (id > 0)
            {
                DeviceParameter dp = _deviceLogic.GetDeviceParameter(id);
                var deviceData = _deviceLogic.GetDeviceData(dp.DeviceId);
                var model = new CreateDeviceParameterModel().PopulateFrom(dp);
                model.DeviceName = deviceData.Title;
                return View(model);
            }

            return View(new CreateDeviceParameterModel());
        }

        [HttpPost]
        public ActionResult Create(CreateDeviceParameterModel data)
        {
            DeviceParameter dp = new DeviceParameter();
            dp.DeviceId = data.DeviceId;
            dp.Channel = data.Channel;
            dp.Parameter = data.Parameter;
            dp.ValueErrorThreshold = data.ValueErrorThreshold;
            dp.ValueWarnThreshold = data.ValueWarnThreshold;
            dp.ValueThresholdDirectionRight = data.ValueThresholdDirectionRight;
            _deviceLogic.SaveOrUpdateDevice(dp);
            return RedirectToAction("Index");
        }
    }
}

HmIpMonitor/HmIpMonitor/Controllers/HomeController.cs
using HmIpMonitor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace HmIpMonitor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HmIpMonitor/HmIpMonitor/Views/Dashboard/Create.cshtml
@model CreateEditDashboardModel
@{
    ViewData["Title"] = "Create Dashboard";
}

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <h4>Dashboard Basisdaten</h4>
    <div class="form-group">
        @Html.LabelFor(x => x.Title, new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(x => x.Id)
        </div>
    </div>
    <hr />
    
    <table class="table">
        @for (var pIndex = 0; pIndex < Model.DeviceParameters.Count; pIndex++)
        {
            <tr>
                <td>@Model.DeviceParameters[pIndex].Title</td>
                <td>
                    <table class="table">
                        @for (var dpIndex = 0; dpIndex < Model.DeviceParameters[pIndex].Parameters.Count; dpIndex++)
                        {
                            <tr>
                                <td>@Model.DeviceParameters[pIndex].Parameters[dpIndex].Parameter</td>
                                <td>@Html.CheckBoxFor(x => x.DeviceParameters[pIndex].Parameters[dpIndex].Active) 
                                    @Html.HiddenFor(x => x.DeviceParameters[pIndex].Parameters[dpIndex].Id)</td>
                            </tr>
                        }
                    </table>
                </td>
            </tr>
        }
    </table>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

HmIpMonitor/HmIpMonitor/Views/Dashboard/Details.cshtml
@model long
@{
    ViewData["Title"] = "Details";
}



<h1>@ViewData["Title"]</h1>

<div class="parameter-main">

</div>

@section scripts{
    <script>
        async function load() {
            while (true) {
                try {
                    await $(".parameter-main").load("/Dashboard/CarPartial/@Model");
                    await new Promise(resolve => {
                        setTimeout(resolve, 5000)
                    });
                } catch (e) {
                    console.error(e);
                }
            }
        }

        load();
    </script>
}

HmIpMonitor/HmIpMonitor/Views/Dashboard/Index.cshtml
@model IEnumerable<HmIpMonitor.EntityFramework.Models.Dashboard>
@{
    ViewData["Title"] = "Dashboard";
}

<h1>@ViewData["Title"]</h1>

<p>@Html.ActionLink("Create New", "Create")</p>

<table class="table">
    <tr><th>Titel</th><th>#Parameters</th><th>Actions</th></tr>
    @foreach (var d in Model)
    {
        <tr>
            <td>@d.Title</td><td>@d.DashboardDeviceParameters.Count</td><td>@Html.ActionLink("Delete", "Delete", new { d.Id }) | 
                @Html.ActionLink("Edit", "Edit", new { d.Id }) |
                @Html.ActionLink("Details", "Details", new { Id = d.Id })</td>
        </tr>
    }
</table>

HmIpMonitor/HmIpMonitor/Views/Device/Create.cshtml
@model CreateDeviceParameterModel

@{
    ViewData["Title"] = "Neuer Eintrag";
}

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm())
{
    <div class = "form-horizontal">
        <h4>Geräteparameter (@Model.DeviceName):</h4>
        <hr />

        <div class="form-group">
            @Html.HiddenFor(x => x.Id)
            @Html.LabelFor(model => model.DeviceId, htmlAttributes:
                new {@class = "control-label col-md-2"})

            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceId, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Channel, htmlAttributes:
                new{ @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Channel, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Parameter, htmlAttributes:
                new{ @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Parameter, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ValueErrorThreshold, htmlAttributes:
                new{ @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueErrorThreshold, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ValueWarnThreshold, htmlAttributes:
                new{ @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueWarnThreshold, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ValueThresholdDirectionRight, htmlAttributes:
                new{ @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.ValueThresholdDirectionRight, new
                {
                    htmlAttributes =
                        new {@class = "form-control"}
                })
            </div>
        </div>
        
        <div class = "form-group">
            <div class = "col-md-offset-2 col-md-10">
                <input type = "submit" value = "Create" class = "btn btn-default"/>
            </div>
        </div>
    </div>
}

HmIpMonitor/HmIpMonitor/Views/Device/Index.cshtml
@model IEnumerable<DeviceIndexModel>
@{
    ViewData["Title"] = "Alle Geräteparameter";
}

<h1>@ViewData["Title"]</h1>

<p>@Html.ActionLink("Create New", "Create")</p>

<table class="table">
    <tr><th>Gerät</th><th>Channel</th><th>Parameter</th><th>Thresholds (E/W/Direction right)</th><th>Actions</th></tr>
    @foreach (var d in Model)
    {
        <tr><td>@d.Title</td><td></td><td></td><td></td></tr>
        @foreach (var dp in d.DeviceParameter)
        {
            <tr>
                <td></td>
                <td>@dp.Channel</td>
                <td>@dp.Parameter</td>
                <td>@dp.ValueErrorThreshold / @dp.ValueWarnThreshold / @dp.ValueThresholdDirectionRight</td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = dp.Id }) |
                    @Html.ActionLink("Edit", "Create", new { id = dp.Id })
                </td>
            </tr>
        }
    }
</table>

HmIpMonitor/HmIpMonitor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HmIpMonitor/HmIpMonitor/Views/Shared/_DashboardDetailsPartial.cshtml
@using HmIpMonitor.Contracts
@model List<HmIpMonitor.Contracts.CcuValueDto>

@functions {

    string GetGroupClass(CcuValueDto value)
    {
        var errorThreshold = value.DeviceParameter.ValueErrorThreshold;
        var warnThreshold = value.DeviceParameter.ValueWarnThreshold;

        if (Math.Abs(errorThreshold - warnThreshold) < 0.1)
        {
            return string.Empty;
        }

        if (value.DeviceParameter.ValueThresholdDirectionRight)
        {
            if (errorThreshold < value.V)
            {
                return "error";
            }

            if (warnThreshold < value.V)
            {
                return "warn";
            }
        }
        else
        {
            if (errorThreshold > value.V)
            {
                return "error";
            }

            if (warnThreshold > value.V)
            {
                return "warn";
            }
        }

        return string.Empty;
    }

}

@foreach (var d in Model)
{
    <div class="parameter-group @GetGroupClass(d)">
        <div class="device" title="@d.DeviceName">@d.DeviceName</div>
        <div class="parameter" title="@d.DeviceParameter.Parameter">@d.DeviceParameter.Parameter</div>
        <div class="divider @GetGroupClass(d)"></div>
        <div class="value">@d.V</div>
    </div>
}

HmIpMonitor/HmIpMonitor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HmIpMonitor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HmIpMonitor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Device" asp-action="Index">Device</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HmIpMonitor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>